apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  nginx.conf: |-
    server {
        listen 443 ssl;
        server_name playsdev.hopto.org;
        root        /var/www;
        index  index.html info.php;

        location / {
        try_files $uri $uri/ =404;
        }

        location ~* .mp3$  {
        root /var/www/mp3;
        types { application/octet-stream .mp3; }

        }

        location /page1 {
        proxy_pass http://localhost:8000;
        }

        location /apache {
        proxy_pass http://localhost:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        }


        location /image2 {
          try_files /image2/cat.png =404;
        }

        location ~*  \.(jpg|jpeg)$ {
          root /var/www/image1;
          #image_filter rotate 180;
        }


        ssl_certificate /etc/letsencrypt/live/playsdev.hopto.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/playsdev.hopto.org/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    }
    server {
            return 301 https://$host$request_uri;


            listen 80 default_server;
            server_name playsdev.hopto.org;
            return 404;
    }


    server {
      listen 8000;
      server_name playsdev.hopto.org;
      location /page1 {
        root /var/www/;
      }
    }


    server {
      listen 9000;
      root /var/www/second_server;
      location / {
        index index.html;
      }
    }
