apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: demo
  template:
    metadata:
      labels:
        project: demo
    spec:
      containers:
        - name: nginx
          image: dilgam/playsdev:nginx-kuber
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-proxy-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
        - name: apache
          image: dilgam/playsdev:apache-kub
          ports:
            - containerPort: 8080
      volumes:
        - name: nginx-proxy-config
          configMap:
            name: {{ .Release.Name }}-configmap
